-- 코드를 입력하세요
WITH S AS (
    SELECT A.BOOK_ID, A.CATEGORY, A.AUTHOR_ID, A.PRICE * SUM(B.SALES) AS B_SALES
    FROM BOOK A JOIN BOOK_SALES B ON A.BOOK_ID = B.BOOK_ID
    WHERE B.SALES_DATE LIKE '2022-01-%'
    GROUP BY A.BOOK_ID
)
SELECT S.AUTHOR_ID, C.AUTHOR_NAME, S.CATEGORY, SUM(S.B_SALES) AS TOTAL_SALES
FROM S JOIN AUTHOR C ON S.AUTHOR_ID = C.AUTHOR_ID
GROUP BY S.AUTHOR_ID, S.CATEGORY
ORDER BY S.AUTHOR_ID, S.CATEGORY DESC;
# SELECT *, SUM(B_SALES) FROM S
# GROUP BY AUTHOR_ID, CATEGORY