-- 코드를 입력하세요 A.NAME as NAME, A.DATETIME
SELECT A.NAME as NAME, A.DATETIME as DATETIME FROM ANIMAL_INS as A
LEFT OUTER JOIN ANIMAL_OUTS as B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.DATETIME IS NULL
ORDER BY A.DATETIME LIMIT 3;
