# # -- 코드를 입력하세요
SELECT MEMBER_NAME,REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE 
FROM MEMBER_PROFILE A JOIN REST_REVIEW B
ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID IN (SELECT MEMBER_ID FROM REST_REVIEW 
GROUP BY MEMBER_ID
HAVING  COUNT(MEMBER_ID) = (SELECT COUNT(MEMBER_ID) FROM REST_REVIEW GROUP BY MEMBER_ID
ORDER BY COUNT(MEMBER_ID) DESC LIMIT 1))
ORDER BY B.REVIEW_DATE, B.REVIEW_TEXT;

# SELECT MEMBER_ID FROM REST_REVIEW 
# GROUP BY MEMBER_ID
# HAVING  COUNT(MEMBER_ID) = (SELECT COUNT(MEMBER_ID) FROM REST_REVIEW GROUP BY MEMBER_ID
# ORDER BY COUNT(MEMBER_ID) DESC LIMIT 1)

# SELECT COUNT(MEMBER_ID) FROM REST_REVIEW GROUP BY MEMBER_ID
# ORDER BY COUNT(MEMBER_ID) DESC LIMIT 1




